<img src="https://github.com/cikicali369-glitch/DSB-Unit-03/blob/main/labs/02%20-%20Classification-LeftHanded/assets/ga-logo.png?raw=1" style="float: left; margin: 20px; height: 55px">

# Lab: Classification: Predicting Left-Handedness from Psychological Factors

---

One way to define the data science process is as follows:

1. Define the problem.
2. Obtain the data.
3. Explore the data.
4. Model the data.
5. Evaluate the model.
6. Answer the problem.

We'll walk through a full data science problem in this lab.

---
## Step 1: Define The Problem.

You're currently a data scientist working at a university. A professor of psychology is attempting to study the relationship between personalities and left-handedness. They have tasked you with gathering evidence so that they may publish.

As a data scientist, you know that any real data science problem must be **specific** and **conclusively answerable**. For example:
- Bad data science problem: "What is the link between obesity and blood pressure?"
    - This is vague and is not conclusively answerable. That is, two people might look at the conclusion and one may say "Sure, the problem has been answered!" and the other may say "The problem has not yet been answered."
- Good data science problem: "Does an association exist between obesity and blood pressure?"
    - This is more specific and is conclusively answerable. The problem specifically is asking for a "Yes" or "No" answer. Based on that, two independent people should both be able to say either "Yes, the problem has been answered" or "No, the problem has not yet been answered."
- Excellent data science problem: "As obesity increases, how does blood pressure change?"
    - This is very specific and is conclusively answerable. The problem specifically seeks to understand the effect of one variable on the other.

### In the context of the left-handedness and personality example, what are three specific and conclusively answerable problems that you could answer using data science?

> You might find it helpful to check out the codebook in the repo for some inspiration.

---
## Step 2: Obtain the data.

### Read in the file titled "data.csv":
> Hint: Despite being saved as a .csv file, you won't be able to simply `pd.read_csv()` this data!

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# Direktan link do fajla na GitHub-u i čitanje sa sep='\t'
url = 'https://raw.githubusercontent.com/cikicali369-glitch/DSB-Unit-03/main/labs/02%20-%20Classification-LeftHanded/data/data.csv'
df = pd.read_csv(url, sep='\t')

# Prikaz prvih nekoliko redova da provjerimo učitavanje
df.head()

,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,...,country,fromgoogle,engnat,age,education,gender,orientation,race,religion,hand
0,4,1,5,1,5,1,5,1,4,1,...,US,2,1,22,3,1,1,3,2,3
1,1,5,1,4,2,5,5,4,1,5,...,CA,2,1,14,1,2,2,6,1,1
2,1,2,1,1,5,4,3,2,1,4,...,NL,2,2,30,4,1,1,1,1,2
3,1,4,1,5,1,4,5,4,3,5,...,US,2,1,18,2,2,5,3,2,2
4,5,1,5,1,5,1,5,1,3,1,...,US,2,1,22,3,1,1,3,2,3

,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,...,country,fromgoogle,engnat,age,education,gender,orientation,race,religion,hand
0,4,1,5,1,5,1,5,1,4,1,...,US,2,1,22,3,1,1,3,2,3
1,1,5,1,4,2,5,5,4,1,5,...,CA,2,1,14,1,2,2,6,1,1
2,1,2,1,1,5,4,3,2,1,4,...,NL,2,2,30,4,1,1,1,1,2
3,1,4,1,5,1,4,5,4,3,5,...,US,2,1,18,2,2,5,3,2,2
4,5,1,5,1,5,1,5,1,3,1,...,US,2,1,22,3,1,1,3,2,3

---

## Step 3: Explore the data.

### Conduct background research:

Domain knowledge is irreplaceable. Figuring out what information is relevant to a problem, or what data would be useful to gather, is a major part of any end-to-end data science project! For this lab, you'll be using a dataset that someone else has put together, rather than collecting the data yourself.

Do some background research about personality and handedness. What features, if any, are likely to help you make good predictions? How well do you think you'll be able to model this? Write a few bullet points summarizing what you believe, and remember to cite external sources.

You don't have to be exhaustive here. Do enough research to form an opinion, and then move on.

> You'll be using the answers to Q1-Q44 for modeling; you can disregard other features, e.g. country, age, internet browser.

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4184 entries, 0 to 4183
Data columns (total 56 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Q1           4184 non-null   int64
 1   Q2           4184 non-null   int64
 2   Q3           4184 non-null   int64
 3   Q4           4184 non-null   int64
 4   Q5           4184 non-null   int64
 5   Q6           4184 non-null   int64
 6   Q7           4184 non-null   int64
 7   Q8           4184 non-null   int64
 8   Q9           4184 non-null   int64
 9   Q10          4184 non-null   int64
 10  Q11          4184 non-null   int64
 11  Q12          4184 non-null   int64
 12  Q13          4184 non-null   int64
 13  Q14          4184 non-null   int64
 14  Q15          4184 non-null   int64
 15  Q16          4184 non-null   int64
 16  Q17          4184 non-null   int64
 17  Q18          4184 non-null   int64
 18  Q19          4184 non-null   int64
 19  Q20          4184 non-null   int64
 20  Q21          4184 non-null   int64
 21  Q22          4184 non-null   int64
 22  Q23          4184 non-null   int64
 23  Q24          4184 non-null   int64
 24  Q25          4184 non-null   int64
 25  Q26          4184 non-null   int64
 26  Q27          4184 non-null   int64
 27  Q28          4184 non-null   int64
 28  Q29          4184 non-null   int64
 29  Q30          4184 non-null   int64
 30  Q31          4184 non-null   int64
 31  Q32          4184 non-null   int64
 32  Q33          4184 non-null   int64
 33  Q34          4184 non-null   int64
 34  Q35          4184 non-null   int64
 35  Q36          4184 non-null   int64
 36  Q37          4184 non-null   int64
 37  Q38          4184 non-null   int64
 38  Q39          4184 non-null   int64
 39  Q40          4184 non-null   int64
 40  Q41          4184 non-null   int64
 41  Q42          4184 non-null   int64
 42  Q43          4184 non-null   int64
 43  Q44          4184 non-null   int64
 44  introelapse  4184 non-null   int64
 45  testelapse   4184 non-null   int64
 46  country      4184 non-null   str
 47  fromgoogle   4184 non-null   int64
 48  engnat       4184 non-null   int64
 49  age          4184 non-null   int64
 50  education    4184 non-null   int64
 51  gender       4184 non-null   int64
 52  orientation  4184 non-null   int64
 53  race         4184 non-null   int64
 54  religion     4184 non-null   int64
 55  hand         4184 non-null   int64
dtypes: int64(55), str(1)
memory usage: 1.8 MB

### Conduct exploratory data analysis on this dataset:

If you haven't already, be sure to check out the codebook in the repo, as that will help in your EDA process.

You might use this section to perform data cleaning if you find it to be necessary.

In [4]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4184 entries, 0 to 4183
Data columns (total 56 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Q1           4184 non-null   int64
 1   Q2           4184 non-null   int64
 2   Q3           4184 non-null   int64
 3   Q4           4184 non-null   int64
 4   Q5           4184 non-null   int64
 5   Q6           4184 non-null   int64
 6   Q7           4184 non-null   int64
 7   Q8           4184 non-null   int64
 8   Q9           4184 non-null   int64
 9   Q10          4184 non-null   int64
 10  Q11          4184 non-null   int64
 11  Q12          4184 non-null   int64
 12  Q13          4184 non-null   int64
 13  Q14          4184 non-null   int64
 14  Q15          4184 non-null   int64
 15  Q16          4184 non-null   int64
 16  Q17          4184 non-null   int64
 17  Q18          4184 non-null   int64
 18  Q19          4184 non-null   int64
 19  Q20          4184 non-null   int64
 20  Q21          4184 non-null   int64
 21  Q22          4184 non-null   int64
 22  Q23          4184 non-null   int64
 23  Q24          4184 non-null   int64
 24  Q25          4184 non-null   int64
 25  Q26          4184 non-null   int64
 26  Q27          4184 non-null   int64
 27  Q28          4184 non-null   int64
 28  Q29          4184 non-null   int64
 29  Q30          4184 non-null   int64
 30  Q31          4184 non-null   int64
 31  Q32          4184 non-null   int64
 32  Q33          4184 non-null   int64
 33  Q34          4184 non-null   int64
 34  Q35          4184 non-null   int64
 35  Q36          4184 non-null   int64
 36  Q37          4184 non-null   int64
 37  Q38          4184 non-null   int64
 38  Q39          4184 non-null   int64
 39  Q40          4184 non-null   int64
 40  Q41          4184 non-null   int64
 41  Q42          4184 non-null   int64
 42  Q43          4184 non-null   int64
 43  Q44          4184 non-null   int64
 44  introelapse  4184 non-null   int64
 45  testelapse   4184 non-null   int64
 46  country      4184 non-null   object
 47  fromgoogle   4184 non-null   int64
 48  engnat       4184 non-null   int64
 49  age          4184 non-null   int64
 50  education    4184 non-null   int64
 51  gender       4184 non-null   int64
 52  orientation  4184 non-null   int64
 53  race         4184 non-null   int64
 54  religion     4184 non-null   int64
 55  hand         4184 non-null   int64
dtypes: int64(55), object(1)
memory usage: 1.8+ MB

,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,...,testelapse,fromgoogle,engnat,age,education,gender,orientation,race,religion,hand
count,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,...,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000,4184.000000
mean,1.962715,3.829589,2.846558,3.186902,2.865440,3.672084,3.216539,3.184512,2.761233,3.522945,...,479.994503,1.576243,1.239962,30.370698,2.317878,1.654398,1.833413,5.013623,2.394359,1.190966
std,1.360291,1.551683,1.664804,1.476879,1.545798,1.342238,1.490733,1.387382,1.511805,1.242890,...,3142.178542,0.494212,0.440882,367.201726,0.874264,0.640915,1.303454,1.970996,2.184164,0.495357
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,7.000000,1.000000,0.000000,13.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,3.000000,1.000000,2.000000,1.000000,3.000000,2.000000,2.000000,1.000000,3.000000,...,186.000000,1.000000,1.000000,18.000000,2.000000,1.000000,1.000000,5.000000,1.000000,1.000000
50%,1.000000,5.000000,3.000000,3.000000,3.000000,4.000000,3.000000,3.000000,3.000000,4.000000,...,242.000000,2.000000,1.000000,21.000000,2.000000,2.000000,1.000000,6.000000,2.000000,1.000000
75%,3.000000,5.000000,5.000000,5.000000,4.000000,5.000000,5.000000,4.000000,4.000000,5.000000,...,324.250000,2.000000,1.000000,27.000000,3.000000,2.000000,2.000000,6.000000,2.000000,1.000000
max,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,...,119834.000000,2.000000,2.000000,23763.000000,4.000000,3.000000,5.000000,7.000000,7.000000,3.000000

### Calculate and interpret the baseline accuracy rate:

In [5]:
# Provjeravamo distribuciju ciljne kolone 'hand' (gdje je rješenje ciljna varijabla)
df['hand'].value_counts(normalize=True)

hand
1    0.846558
2    0.108031
3    0.042782
0    0.002629
Name: proportion, dtype: float64

### Short answer questions:

In this lab you'll use K-nearest neighbors and logistic regression to model
handedness based off of psychological factors.

Answer the following related questions; your answers may be in bullet points
**on your own words**

#### Describe the difference between regression and classification problems:

In [ ]:
#Regression predicts a continuous numeric value (e.g., price, height, temperature), while classification predicts a discrete class label or category (e.g., left-handed/right-handed, spam/not-spam).

#### Considering $k$-nearest neighbors, describe the relationship between $k$ and the bias-variance tradeoff:

In [ ]:
#A small k (e.g., k=3) results in low bias and high variance, which can easily cause overfitting. A large k results in high bias and low variance, which can lead to underfitting.

#### Why do we often standardize predictor variables when using $k$-nearest neighbors?

In [ ]:
#KNN uses Euclidean distance between points. If variables are not on the same scale, those with larger ranges will dominate the distance formula. Standardization ensures every variable has an equal influence.

#### Do you think we should standardize the explanatory variables for this problem? Why or why not?

In [ ]:
#Yes. Although Q1-Q44 are already on the same scale (1 to 5), standardization sets the mean to 0 and variance to 1, which is a standard and recommended practice for distance-based algorithms.

#### How do we settle on $k$ for a $k$-nearest neighbors model?

In [ ]:
#We use cross-validation or a validation/test dataset by trying out different values of k and choosing the one that yields the lowest error rate, i.e., the best performance.

#### What is the default type of regularization for logistic regression as implemented in scikit-learn? (You might [check the documentation](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html).)

In [ ]:
#The default regularization for logistic regression in scikit-learn is L2 regularization (Ridge) (penalty='l2').

#### [Bonus - Optional] Describe the relationship between the scikit-learn `LogisticRegression` argument `C` and regularization strength:

In [ ]:
#The C parameter is inversely proportional to regularization strength (C = 1 / alpha). A smaller C value means stronger regularization, while a larger C value means weaker regularization.

#### Describe the relationship between regularization strength and the bias-variance tradeoff:

In [ ]:
#Stronger regularization increases bias and decreases variance, helping to prevent overfitting. Weaker regularization decreases bias and increases variance.

#### Logistic regression is considered more interpretable than $k$-nearest neighbors. Explain why.

In [ ]:
#Logistic regression assigns clear coefficients to each variable indicating the direction and magnitude of their impact on the outcome. KNN is a non-parametric 'black-box' model based on neighbors without global weights.

---

## Step 4 & 5 Modeling: $k$-nearest neighbors

### Train-test split your data:

Your explanatory variables should be all Q columns.

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

q_cols = [f'Q{i}' for i in range(1, 45)]
X = df[q_cols]
y = df['hand']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

ss = StandardScaler()
X_train_sc = ss.fit_transform(X_train)
X_test_sc = ss.transform(X_test)

### Create and fit four separate $k$-nearest neighbors models:

### Model 1: one with $k = 3$:

In [7]:
from sklearn.neighbors import KNeighborsClassifier

knn_3 = KNeighborsClassifier(n_neighbors=3)
knn_3.fit(X_train_sc, y_train)

KNeighborsClassifier(n_neighbors=3)

#### Model 2: one with $k = 5$

In [8]:
knn_5 = KNeighborsClassifier(n_neighbors=5)
knn_5.fit(X_train_sc, y_train)

KNeighborsClassifier()

#### Model 3: one with $k = 15$

In [9]:
knn_15 = KNeighborsClassifier(n_neighbors=15)
knn_15.fit(X_train_sc, y_train)

KNeighborsClassifier(n_neighbors=15)

#### Model 4: one with $k = 25$:

In [10]:
knn_25 = KNeighborsClassifier(n_neighbors=25)
knn_25.fit(X_train_sc, y_train)

KNeighborsClassifier(n_neighbors=25)

### Evaluate your models:

Evaluate each of your four models on the training and testing sets, and
interpret the four scores.

Are any of your models overfit or underfit?

Do any of your models beat the baseline accuracy rate?

In [11]:
knn_models = {"k=3": knn_3, "k=5": knn_5, "k=15": knn_15, "k=25": knn_25}

for name, model in knn_models.items():
    train_acc = model.score(X_train_sc, y_train)
    test_acc = model.score(X_test_sc, y_test)
    print(f"KNN ({name}) -> Train Acc: {train_acc:.4f} | Test Acc: {test_acc:.4f}")

KNN (k=3) -> Train Acc: 0.8682 | Test Acc: 0.7921
KNN (k=5) -> Train Acc: 0.8542 | Test Acc: 0.8172
KNN (k=15) -> Train Acc: 0.8500 | Test Acc: 0.8327
KNN (k=25) -> Train Acc: 0.8500 | Test Acc: 0.8327

---

## Step 4 & 5 Modeling: logistic regression

### Create and fit four separate logistic regression models:

*(Hint: Be careful with how you specify $\alpha$ in your model!)*
Note: You can use the same train and test data as above.

#### Model 1 : one with LASSO and $\alpha = 1$

In [12]:
from sklearn.linear_model import LogisticRegression

lr_lasso_1 = LogisticRegression(penalty='l1', C=1.0, solver='liblinear', random_state=42)
lr_lasso_1.fit(X_train_sc, y_train)

LogisticRegression(penalty='l1', random_state=42, solver='liblinear')

#### Model 2 : one with LASSO and $\alpha = 10$

In [13]:
lr_lasso_10 = LogisticRegression(penalty='l1', C=0.1, solver='liblinear', random_state=42)
lr_lasso_10.fit(X_train_sc, y_train)

LogisticRegression(C=0.1, penalty='l1', random_state=42, solver='liblinear')

#### Model 3 : one with RIDGE and $\alpha = 1$

In [14]:
lr_ridge_1 = LogisticRegression(penalty='l2', C=1.0, random_state=42)
lr_ridge_1.fit(X_train_sc, y_train)

LogisticRegression(random_state=42)

#### Model 4 : one with RIDGE and $\alpha = 10$

In [15]:
lr_ridge_10 = LogisticRegression(penalty='l2', C=0.1, random_state=42)
lr_ridge_10.fit(X_train_sc, y_train)

LogisticRegression(C=0.1, random_state=42)

### Evaluate your models:

Evaluate each of your four models on the training and testing sets, and
interpret the four scores.

Are any of your models overfit or underfit?

Do any of your models beat the baseline accuracy rate?

In [16]:
lr_models = {
    "LASSO (alpha=1)": lr_lasso_1,
    "LASSO (alpha=10)": lr_lasso_10,
    "RIDGE (alpha=1)": lr_ridge_1,
    "RIDGE (alpha=10)": lr_ridge_10
}

for name, model in lr_models.items():
    train_acc = model.score(X_train_sc, y_train)
    test_acc = model.score(X_test_sc, y_test)
    print(f"{name} -> Train Acc: {train_acc:.4f} | Test Acc: {test_acc:.4f}")

LASSO (alpha=1) -> Train Acc: 0.8500 | Test Acc: 0.8327
LASSO (alpha=10) -> Train Acc: 0.8500 | Test Acc: 0.8327
RIDGE (alpha=1) -> Train Acc: 0.8503 | Test Acc: 0.8327
RIDGE (alpha=10) -> Train Acc: 0.8503 | Test Acc: 0.8327

---

## Step 6: Answer the problem.

Are any of your models worth moving forward with? What are the "best" models?

In [ ]:
#None of the tested models manage to significantly outperform the baseline accuracy (around 84.6% corresponding to the majority class). This tells us that the psychological questionnaires Q1-Q44 do not have strong predictive power over left-handedness, and these models are not suitable for practical application in this research.